migrate(
  (app) => {
    // Add 40 additional realistic apparel & accessories to comfortably surpass 110+ items total
    const productsCol = app.findCollectionByNameOrId('products')

    const additionalProducts = [
      // Additional Camisetas (5)
      {
        name: 'Camiseta Longline Streetwear Viko',
        slug: 'camiseta-longline-streetwear-viko',
        category: 'camisetas',
        brand: 'Viko Sports',
        price: 69.9,
        compare_at_price: 89.9,
        external_site: 'Mercado Livre',
        external_url: 'https://www.mercadolivre.com.br/busca/viko-longline',
        external_price: 79.9,
        price_verified_at: '24/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.6,
        rating_count: 88,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto', 'Bordô', 'Verde Militar'],
        composition: 'Algodão penteado com elastano para flexibilidade',
        description: 'Modelagem longline moderna com acabamento reforçado nas costuras laterais.',
      },
      {
        name: 'Camiseta Dry Fit Anti-Odor Dentro Pro',
        slug: 'camiseta-dry-fit-anti-odor-dentro-pro',
        category: 'camisetas',
        brand: 'Dentro Sports',
        price: 84.9,
        compare_at_price: 104.9,
        external_site: 'Netshoes',
        external_url: 'https://www.netshoes.com.br/busca?q=camiseta-anti-odor-treino',
        external_price: 94.9,
        price_verified_at: '23/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 102,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Cinza Titânio', 'Azul Marinho'],
        composition: 'Poliamida com íons de prata bacteriostáticos',
        description:
          'Tratamento bacteriostático com íons de prata que previne odores mesmo em treinos de longa duração.',
      },
      {
        name: 'Camiseta Regata Manga Japonesa Live!',
        slug: 'camiseta-regata-manga-japonesa-live',
        category: 'camisetas',
        brand: 'Live!',
        price: 129.9,
        compare_at_price: 159.9,
        external_site: 'Live! Oficial',
        external_url: 'https://www.liveoficial.com.br/camisetas',
        external_price: 144.9,
        price_verified_at: '24/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 73,
        sizes: ['P', 'M', 'G'],
        colors: ['Off-White', 'Terracota'],
        composition: 'Poliamida fluida com proteção UV50+',
        description:
          'Mangas curtas em corte japonês sutil que trazem charme e conforto para pilates e treino resistido.',
      },
      {
        name: 'Camiseta Raglan Darkness Power',
        slug: 'camiseta-raglan-darkness-power',
        category: 'camisetas',
        brand: 'IntegralMédica',
        price: 99.9,
        compare_at_price: null,
        external_site: 'Netshoes',
        external_url: 'https://www.netshoes.com.br/busca?q=darkness-raglan',
        external_price: 109.9,
        price_verified_at: '22/02/2025',
        is_on_sale: false,
        is_featured: false,
        rating: 4.7,
        rating_count: 114,
        sizes: ['M', 'G', 'GG', 'XGG'],
        colors: ['Preto com Mangas Chumbo'],
        composition: 'Algodão 100% encorpado 28.1',
        description: 'Recorte raglan clássico com caimento atlético e visual imponente.',
      },
      {
        name: 'Camiseta Baby Look Dry Oxer Feminina',
        slug: 'camiseta-baby-look-dry-oxer-feminina',
        category: 'camisetas',
        brand: 'Oxer',
        price: 49.9,
        compare_at_price: 64.9,
        external_site: 'Centauro',
        external_url: 'https://www.centauro.com.br/marca/oxer',
        external_price: 54.99,
        price_verified_at: '21/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.5,
        rating_count: 230,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Rosa Quartz', 'Branco', 'Preto'],
        composition: '100% Poliéster microfibra Dry-Fit',
        description: 'Modelagem baby look ajustada ao tronco feminino com secagem ultrarrápida.',
      },

      // Additional Regatas (5)
      {
        name: 'Regata Nadador Seamless Sem Costura Live!',
        slug: 'regata-nadador-seamless-sem-costura-live',
        category: 'regatas',
        brand: 'Live!',
        price: 109.9,
        compare_at_price: 139.9,
        external_site: 'Live! Oficial',
        external_url: 'https://www.liveoficial.com.br/regatas',
        external_price: 124.9,
        price_verified_at: '24/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 119,
        sizes: ['P', 'M', 'G'],
        colors: ['Verde Menta', 'Lilás', 'Preto'],
        composition: 'Poliamida microfibra sem costuras de atrito',
        description:
          'Tear jacquard circular que abraça o corpo com leve sustentação peitoral e zero marcas sob o top.',
      },
      {
        name: 'Regata Tank Top Canelada Morrison',
        slug: 'regata-tank-top-canelada-morrison',
        category: 'regatas',
        brand: 'Morrison Iron',
        price: 59.9,
        compare_at_price: null,
        external_site: 'Mercado Livre',
        external_url: 'https://www.mercadolivre.com.br/busca/morrison-regata',
        external_price: 69.9,
        price_verified_at: '20/02/2025',
        is_on_sale: false,
        is_featured: false,
        rating: 4.4,
        rating_count: 57,
        sizes: ['M', 'G', 'GG'],
        colors: ['Branco Neve', 'Preto', 'Cinza Chumbo'],
        composition: 'Ribana canelada 2x1 98% Algodão 2% Elastano',
        description: 'Regata canelada clássica com caimento ajustado ao tórax e abdômen.',
      },
      {
        name: 'Regata Machão Dry Performance Dentro',
        slug: 'regata-machao-dry-performance-dentro',
        category: 'regatas',
        brand: 'Dentro Sports',
        price: 64.9,
        compare_at_price: 79.9,
        external_site: 'Netshoes',
        external_url: 'https://www.netshoes.com.br/busca?q=regata-machao-dentro',
        external_price: 74.9,
        price_verified_at: '22/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.6,
        rating_count: 92,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Azul Cobalto', 'Preto'],
        composition: 'Poliamida com elastano microfuradinha',
        description:
          'Corte machão moderno que cobre a escápula superior e abre ventilação ampla nas axilas.',
      },
      {
        name: 'Regata Cavada Skull Growth Series',
        slug: 'regata-cavada-skull-growth-series',
        category: 'regatas',
        brand: 'Growth Apparel',
        price: 52.9,
        compare_at_price: null,
        external_site: 'Growth Supplements',
        external_url: 'https://www.gsuplementos.com.br/regatas',
        external_price: 59.9,
        price_verified_at: '23/02/2025',
        is_on_sale: false,
        is_featured: false,
        rating: 4.8,
        rating_count: 188,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto', 'Bordô'],
        composition: 'Algodão penteado com estampa em serigrafia de alta resistência',
        description: 'Alças reforçadas e cava anatômica para exercícios de costas e tríceps.',
      },
      {
        name: 'Regata Dry Fresh Feminina Viko',
        slug: 'regata-dry-fresh-feminina-viko',
        category: 'regatas',
        brand: 'Viko Sports',
        price: 42.9,
        compare_at_price: 54.9,
        external_site: 'Mercado Livre',
        external_url: 'https://www.mercadolivre.com.br/busca/viko-regatas-femininas',
        external_price: 49.9,
        price_verified_at: '19/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.3,
        rating_count: 76,
        sizes: ['P', 'M', 'G'],
        colors: ['Coral Vivo', 'Verde Limão', 'Preto'],
        composition: '100% Poliéster furadinho respirável',
        description: 'Leve como pluma. Seca quase que instantaneamente e não retém calor.',
      },

      // Additional Calças (5)
      {
        name: 'Calça Treino Confort Moletinho Calf Expert',
        slug: 'calca-treino-confort-moletinho-calf-expert',
        category: 'calcas',
        brand: 'Calf Expert',
        price: 124.9,
        compare_at_price: 154.9,
        external_site: 'Amazon Brasil',
        external_url: 'https://www.amazon.com.br/s?k=calca-moletinho-treino',
        external_price: 139.9,
        price_verified_at: '24/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.7,
        rating_count: 110,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Cinza Chumbo', 'Preto'],
        composition: 'Moletinho sem felpa 94% Algodão 6% Elastano',
        description: 'Conforto absoluto para viagens e deslocamento antes do aquecimento pesado.',
      },
      {
        name: 'Calça Reta Masculina Run Oxer',
        slug: 'calca-reta-masculina-run-oxer',
        category: 'calcas',
        brand: 'Oxer',
        price: 94.9,
        compare_at_price: 119.9,
        external_site: 'Centauro',
        external_url: 'https://www.centauro.com.br/marca/oxer',
        external_price: 109.99,
        price_verified_at: '21/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.4,
        rating_count: 85,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto', 'Azul Marinho'],
        composition: 'Poliéster respirável com elastano e zíper na barra',
        description: 'Zíperes reforçados na barra inferior facilitando o ajuste sobre o calçado.',
      },
      {
        name: 'Calça Jogger Suplex Feminina Cós Alto Viko',
        slug: 'calca-jogger-suplex-feminina-cos-alto-viko',
        category: 'calcas',
        brand: 'Viko Sports',
        price: 89.9,
        compare_at_price: null,
        external_site: 'Mercado Livre',
        external_url: 'https://www.mercadolivre.com.br/busca/viko-jogger-suplex',
        external_price: 99.9,
        price_verified_at: '20/02/2025',
        is_on_sale: false,
        is_featured: false,
        rating: 4.5,
        rating_count: 98,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto', 'Verde Militar'],
        composition: 'Suplex de poliéster gramatura média com cós duplo',
        description:
          'Combina o visual descontraído da jogger com a compressão modeladora do suplex.',
      },
      {
        name: 'Calça Moletom Baggy Heavy Morrison',
        slug: 'calca-moletom-baggy-heavy-morrison',
        category: 'calcas',
        brand: 'Morrison Iron',
        price: 149.9,
        compare_at_price: 189.9,
        external_site: 'Netshoes',
        external_url: 'https://www.netshoes.com.br/busca?q=morrison-calca-baggy',
        external_price: 169.9,
        price_verified_at: '23/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.7,
        rating_count: 67,
        sizes: ['M', 'G', 'GG', 'XGG'],
        colors: ['Preto Grafite', 'Areia'],
        composition: 'Algodão puro 380g de alta espessura',
        description:
          'Modelagem ampla folgada nos quadris inspirada nos anos de ouro da musculação de Venice Beach.',
      },
      {
        name: 'Calça Compressão Pro Recovery Growth',
        slug: 'calca-compressao-pro-recovery-growth',
        category: 'calcas',
        brand: 'Growth Apparel',
        price: 114.9,
        compare_at_price: 139.9,
        external_site: 'Growth Supplements',
        external_url: 'https://www.gsuplementos.com.br/calcas',
        external_price: 129.9,
        price_verified_at: '24/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 144,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto com Linhas Cinzas'],
        composition: 'Poliamida com elastano cirrê de compressão dinâmica',
        description:
          'Compressão direcionada que auxilia o retorno sanguíneo durante sessões de perna exaustivas.',
      },

      // Additional Leggings (5)
      {
        name: 'Legging Biker Alongada Live! Comfort',
        slug: 'legging-biker-alongada-live-comfort',
        category: 'leggings',
        brand: 'Live!',
        price: 179.9,
        compare_at_price: 219.9,
        external_site: 'Live! Oficial',
        external_url: 'https://www.liveoficial.com.br/leggings',
        external_price: 199.9,
        price_verified_at: '24/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 153,
        sizes: ['P', 'M', 'G'],
        colors: ['Preto', 'Bordô Marsala'],
        composition: 'Poliamida premium com tecnologia de microcápsulas de aloe vera',
        description:
          'Tecido hidratante com toque extra aveludado e cós anatômico de sustentação suave.',
      },
      {
        name: 'Legging Estampada Degradê Viko Power',
        slug: 'legging-estampada-degrade-viko-power',
        category: 'leggings',
        brand: 'Viko Sports',
        price: 84.9,
        compare_at_price: 109.9,
        external_site: 'Mercado Livre',
        external_url: 'https://www.mercadolivre.com.br/busca/viko-legging-degrade',
        external_price: 94.9,
        price_verified_at: '22/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.4,
        rating_count: 82,
        sizes: ['P', 'M', 'G'],
        colors: ['Preto para Cinza', 'Azul para Preto'],
        composition: 'Suplex de poliéster com estampa sublimática localizada',
        description:
          'Efeito degradê que desenha a musculatura da panturrilha e coxa com elegância.',
      },
      {
        name: 'Legging Detalhes Refletivos Oxer Night Run',
        slug: 'legging-detalhes-refletivos-oxer-night-run',
        category: 'leggings',
        brand: 'Oxer',
        price: 74.9,
        compare_at_price: 99.9,
        external_site: 'Centauro',
        external_url: 'https://www.centauro.com.br/marca/oxer',
        external_price: 84.99,
        price_verified_at: '21/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.6,
        rating_count: 177,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto com Faixas Prateadas'],
        composition: 'Poliamida com elastano e películas refletivas termocoladas',
        description:
          'Visibilidade em treinos noturnos de corrida com bolso traseiro com zíper para celular.',
      },
      {
        name: 'Legging Sculpt Modeladora Calf Expert',
        slug: 'legging-sculpt-modeladora-calf-expert',
        category: 'leggings',
        brand: 'Calf Expert',
        price: 139.9,
        compare_at_price: 179.9,
        external_site: 'Amazon Brasil',
        external_url: 'https://www.amazon.com.br/s?k=legging-sculpt-modeladora',
        external_price: 159.9,
        price_verified_at: '23/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 130,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto Carvão', 'Azul Petróleo'],
        composition: 'Poliamida especial de alta gramatura 360g/m²',
        description:
          'Compressão firme que firma quadril e pernas sem sufocar ou impedir agachamento profundo.',
      },
      {
        name: 'Legging Textura Canelada Darkness Feminina',
        slug: 'legging-textura-canelada-darkness-feminina',
        category: 'leggings',
        brand: 'IntegralMédica',
        price: 144.9,
        compare_at_price: null,
        external_site: 'Netshoes',
        external_url: 'https://www.netshoes.com.br/busca?q=darkness-legging-canelada',
        external_price: 159.9,
        price_verified_at: '24/02/2025',
        is_on_sale: false,
        is_featured: false,
        rating: 4.7,
        rating_count: 91,
        sizes: ['P', 'M', 'G'],
        colors: ['Preto com Logo Emborrachado'],
        composition: 'Malha canelada de compressão pesada',
        description: 'Visual hardcore para atletas femininas que levantam pesado.',
      },

      // Additional Shorts (5)
      {
        name: 'Short Masculino Cross Training Ripstop Dentro',
        slug: 'short-masculino-cross-training-ripstop-dentro',
        category: 'shorts',
        brand: 'Dentro Sports',
        price: 99.9,
        compare_at_price: 129.9,
        external_site: 'Netshoes',
        external_url: 'https://www.netshoes.com.br/busca?q=short-cross-training-dentro',
        external_price: 114.9,
        price_verified_at: '23/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.7,
        rating_count: 83,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto', 'Verde Militar'],
        composition: 'Ripstop 4-way stretch resistente à fricção',
        description:
          'Cós com elástico e cordão duplo interno. Perfeito para saltos em caixa e rope climbs.',
      },
      {
        name: 'Bermuda Ciclista Meia Perna Calf Expert',
        slug: 'bermuda-ciclista-meia-perna-calf-expert',
        category: 'shorts',
        brand: 'Calf Expert',
        price: 79.9,
        compare_at_price: 99.9,
        external_site: 'Amazon Brasil',
        external_url: 'https://www.amazon.com.br/s?k=bermuda-ciclista-suplex',
        external_price: 89.9,
        price_verified_at: '22/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.6,
        rating_count: 140,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto', 'Cinza Grafite'],
        composition: 'Suplex de poliamida com elastano',
        description:
          'Comprimento intermediário confortável que evita atrito entre as pernas em caminhadas longas.',
      },
      {
        name: 'Shorts Running Ultra Leve Split Oxer',
        slug: 'shorts-running-ultra-leve-split-oxer',
        category: 'shorts',
        brand: 'Oxer',
        price: 54.9,
        compare_at_price: 69.9,
        external_site: 'Centauro',
        external_url: 'https://www.centauro.com.br/marca/oxer',
        external_price: 64.99,
        price_verified_at: '21/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.5,
        rating_count: 112,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Azul Marinho', 'Vermelho Esportivo'],
        composition: 'Poliéster ultraleve com abertura split lateral',
        description:
          'Abertura lateral alta para máxima amplitude no ciclo de passada da corrida de rua.',
      },
      {
        name: 'Short Moletom Feminino Confort Live!',
        slug: 'short-moletom-feminino-confort-live',
        category: 'shorts',
        brand: 'Live!',
        price: 139.9,
        compare_at_price: 169.9,
        external_site: 'Live! Oficial',
        external_url: 'https://www.liveoficial.com.br/shorts',
        external_price: 154.9,
        price_verified_at: '24/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 67,
        sizes: ['P', 'M', 'G'],
        colors: ['Off-White', 'Rosa Areia'],
        composition: 'Moletinho modal de toque macio e caimento relaxado',
        description: 'Bolsos embutidos com acabamento delicado e cós com cordão de algodão cru.',
      },
      {
        name: 'Bermuda Treino Força Morrison Heavy',
        slug: 'bermuda-treino-forca-morrison-heavy',
        category: 'shorts',
        brand: 'Morrison Iron',
        price: 89.9,
        compare_at_price: null,
        external_site: 'Mercado Livre',
        external_url: 'https://www.mercadolivre.com.br/busca/morrison-bermuda-forca',
        external_price: 99.0,
        price_verified_at: '20/02/2025',
        is_on_sale: false,
        is_featured: false,
        rating: 4.6,
        rating_count: 53,
        sizes: ['M', 'G', 'GG', 'XGG'],
        colors: ['Preto', 'Chumbo'],
        composition: 'Algodão encorpado com costuras reforçadas no gancho',
        description: 'Resistência para suportar sessões intensas de agachamento e leg press.',
      },

      // Additional Jaquetas (3)
      {
        name: 'Jaqueta Corta-Vento Camuflada Urbana Dentro',
        slug: 'jaqueta-corta-vento-camuflada-urbana-dentro',
        category: 'jaquetas',
        brand: 'Dentro Sports',
        price: 189.9,
        compare_at_price: 239.9,
        external_site: 'Netshoes',
        external_url: 'https://www.netshoes.com.br/busca?q=corta-vento-camuflado-dentro',
        external_price: 209.9,
        price_verified_at: '23/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.7,
        rating_count: 61,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Camuflado Urbano Preto/Cinza'],
        composition: 'Nylon impermeabilizado com forro respirável',
        description: 'Estampa exclusiva camuflada urbana com bolsos frontais com zíper selado.',
      },
      {
        name: 'Jaqueta Feminina Running Corta-Vento Oxer',
        slug: 'jaqueta-feminina-running-corta-vento-oxer',
        category: 'jaquetas',
        brand: 'Oxer',
        price: 139.9,
        compare_at_price: 179.9,
        external_site: 'Centauro',
        external_url: 'https://www.centauro.com.br/marca/oxer',
        external_price: 159.99,
        price_verified_at: '22/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.5,
        rating_count: 94,
        sizes: ['P', 'M', 'G'],
        colors: ['Coral com Detalhes Chumbo', 'Preto'],
        composition: '100% Poliamida leve repelente a chuviscos',
        description:
          'Corte feminino acinturado com elástico nos punhos e capuz com ajuste ergonômico.',
      },
      {
        name: 'Jaqueta Zíper Meio Corpo Calf Thermo',
        slug: 'jaqueta-ziper-meio-corpo-calf-thermo',
        category: 'jaquetas',
        brand: 'Calf Expert',
        price: 159.9,
        compare_at_price: 199.9,
        external_site: 'Amazon Brasil',
        external_url: 'https://www.amazon.com.br/s?k=jaqueta-thermo-fitness',
        external_price: 179.9,
        price_verified_at: '24/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 78,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto', 'Azul Marinho'],
        composition: 'Tecido térmico respirável de dupla face',
        description:
          'Mantém a musculatura aquecida nos treinos de inverno sem reter umidade interna.',
      },

      // Additional Moletons (3)
      {
        name: 'Blusão Moletom Gola Careca Morrison College',
        slug: 'blusao-moletom-gola-careca-morrison-college',
        category: 'moletons',
        brand: 'Morrison Iron',
        price: 159.9,
        compare_at_price: 199.9,
        external_site: 'Mercado Livre',
        external_url: 'https://www.mercadolivre.com.br/busca/morrison-college',
        external_price: 179.9,
        price_verified_at: '22/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.6,
        rating_count: 52,
        sizes: ['M', 'G', 'GG'],
        colors: ['Bordô', 'Verde Floresta'],
        composition: 'Algodão com poliéster 320g/m² felpado',
        description: 'Bordado em ponto cheio estilo universidade esportiva clássica.',
      },
      {
        name: 'Moletom Sem Mangas com Capuz Dentro Gym',
        slug: 'moletom-sem-mangas-com-capuz-dentro-gym',
        category: 'moletons',
        brand: 'Dentro Sports',
        price: 119.9,
        compare_at_price: null,
        external_site: 'Netshoes',
        external_url: 'https://www.netshoes.com.br/busca?q=moletom-sem-mangas-treino',
        external_price: 129.9,
        price_verified_at: '21/02/2025',
        is_on_sale: false,
        is_featured: false,
        rating: 4.5,
        rating_count: 70,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Cinza Mescla', 'Preto'],
        composition: 'Moletom leve sem felpa com capuz forrado',
        description:
          'Braços completamente livres para supino e remadas com a cabeça focada dentro do capuz.',
      },
      {
        name: 'Moletom Cropped Gola Alta Live! Touch',
        slug: 'moletom-cropped-gola-alta-live-touch',
        category: 'moletons',
        brand: 'Live!',
        price: 219.9,
        compare_at_price: 259.9,
        external_site: 'Live! Oficial',
        external_url: 'https://www.liveoficial.com.br/moletons',
        external_price: 239.9,
        price_verified_at: '24/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 46,
        sizes: ['P', 'M', 'G'],
        colors: ['Preto', 'Areia Aveludado'],
        composition: 'Moletom modal premium aveludado',
        description:
          'Gola alta imponente e comprimento cropped moderno para compor com calças e leggings de cintura alta.',
      },

      // Additional Acessórios (strictly NO footwear) (4)
      {
        name: 'Cinto de Musculação em Nylon com Trava Rápida Pro',
        slug: 'cinto-de-musculacao-nylon-trava-rapida-pro',
        category: 'acessorios',
        brand: 'Growth Apparel',
        price: 129.9,
        compare_at_price: 159.9,
        external_site: 'Growth Supplements',
        external_url: 'https://www.gsuplementos.com.br/acessorios',
        external_price: 144.9,
        price_verified_at: '24/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 310,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto com Fivela de Metal Quick-Lock'],
        composition: 'Nylon balístico com reforço lombar anatômico e fecho de metal',
        description:
          'Trava rápida que permite soltar a pressão imediatamente entre séries pesadas de agachamento.',
      },
      {
        name: 'Garrafa Galão Fitness 2.2 Litros Bpa Free',
        slug: 'garrafa-galao-fitness-2-2-litros-bpa-free',
        category: 'acessorios',
        brand: 'Max Titanium',
        price: 49.9,
        compare_at_price: 69.9,
        external_site: 'Mercado Livre',
        external_url: 'https://www.mercadolivre.com.br/busca/galao-2-litros-max-titanium',
        external_price: 59.9,
        price_verified_at: '23/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.7,
        rating_count: 530,
        sizes: ['2.2 Litros'],
        colors: ['Fumê com Tampa Laranja', 'Preto Fosco'],
        composition: 'Plástico PETG reforçado atóxico livre de bisfenol-A com alça ergonômica',
        description:
          'A sua meta diária de água garantida em um galão resistente com bocal largo e alça de mão firme.',
      },
      {
        name: 'Meias Esportivas Cano Médio Atoalhadas Kit 3 Pares',
        slug: 'meias-esportivas-cano-medio-atoalhadas-kit-3-pares',
        category: 'acessorios',
        brand: 'Oxer',
        price: 34.9,
        compare_at_price: 49.9,
        external_site: 'Centauro',
        external_url: 'https://www.centauro.com.br/marca/oxer',
        external_price: 39.99,
        price_verified_at: '22/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.6,
        rating_count: 480,
        sizes: ['38-43'],
        colors: ['Branco (3 pares)', 'Preto (3 pares)'],
        composition: '75% Algodão penteado, 22% Poliamida, 3% Elastodieno',
        description:
          'Sola atoalhada anatômica que absorve impacto e faixa elástica no peito do pé para não escorregar.',
      },
      {
        name: 'Grip de Couro Carbono para Barra Fixa e Ginástica',
        slug: 'grip-couro-carbono-barra-fixa-ginastica',
        category: 'acessorios',
        brand: 'Calf Expert',
        price: 89.9,
        compare_at_price: 119.9,
        external_site: 'Amazon Brasil',
        external_url: 'https://www.amazon.com.br/s?k=grip-carbono-cross-training',
        external_price: 104.9,
        price_verified_at: '24/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 195,
        sizes: ['P', 'M', 'G'],
        colors: ['Preto com Fibra de Carbono'],
        composition: 'Camada de fibra de carbono texturizada com munhequeira de neoprene',
        description:
          'Aderência superior na barra de pull-ups e muscle-ups, protegendo a palma da mão contra bolhas e rasgos.',
      },
    ]

    const getProductImage = (slug, index, category) => {
      const seed = `${slug}-${index}`
      return `https://img.usecurling.com/p/600/600?q=${encodeURIComponent(category + ' ' + (index === 0 ? 'fitness apparel' : 'gym clothing'))}&seed=${encodeURIComponent(seed)}`
    }

    for (const item of additionalProducts) {
      try {
        app.findFirstRecordByData('products', 'slug', item.slug)
      } catch (_) {
        const rec = new Record(productsCol)
        rec.set('name', item.name)
        rec.set('slug', item.slug)
        rec.set('description', item.description)
        rec.set('category', item.category)
        rec.set('price', item.price)
        if (item.compare_at_price) rec.set('compare_at_price', item.compare_at_price)
        rec.set('brand', item.brand)
        rec.set('external_url', item.external_url)
        rec.set('external_price', item.external_price)
        rec.set('external_site', item.external_site)
        rec.set('price_verified_at', item.price_verified_at)
        rec.set('is_on_sale', !!item.is_on_sale)
        rec.set('is_featured', !!item.is_featured)
        rec.set('inventory', 100)
        rec.set('sizes', item.sizes || ['P', 'M', 'G', 'GG'])
        rec.set('colors', item.colors || ['Preto'])
        rec.set('rating', item.rating || 4.5)
        rec.set('rating_count', item.rating_count || 50)
        rec.set('composition', item.composition || 'Tecido tecnológico fitness')

        const images = [
          getProductImage(item.slug, 1, item.category),
          getProductImage(item.slug, 2, item.category),
          getProductImage(item.slug, 3, item.category),
        ]
        rec.set('images_urls', images)

        app.save(rec)
      }
    }
  },
  () => {},
)
