/**
 * Migration 0008: Add 6 New Brazilian Fitness Apparel Brands with 20% Discount
 * - Alto Giro: 11 produtos
 * - Honey Be: 11 produtos
 * - DLK: 11 produtos
 * - Live! Oficial: 11 produtos
 * - De Corpo: 11 produtos
 * - WonderSize: 11 produtos
 *
 * Regras:
 * - Só roupas e acessórios fitness (sem tênis/calçados)
 * - 20% de desconto aplicado (price = round(external_price * 0.8), compare_at_price = external_price, is_on_sale = true)
 * - Categorias oficiais válidas: camisetas, regatas, calcas, leggings, shorts, jaquetas, moletons, acessorios
 * - Imagens deduplicadas e verificáveis por produto
 */

migrate(
  (app) => {
    const productsCol = app.findCollectionByNameOrId('products')

    const newBrandProducts = [
      // ==========================================
      // 1. ALTO GIRO (11 produtos - 20% OFF)
      // "Reconhecida por unir inovação, estilo sofisticado e alta performance, oferecendo peças voltadas tanto para o esporte quanto para o uso casual."
      // ==========================================
      {
        name: 'Legging Cós Alto Zíper Frente Alto Giro',
        slug: 'legging-cos-alto-ziper-frente-alto-giro',
        category: 'leggings',
        brand: 'Alto Giro',
        external_price: 319.9,
        compare_at_price: 319.9,
        price: 255.92,
        external_site: 'Alto Giro Loja Oficial',
        external_url: 'https://altogiro.com.br/products/legging-cos-alto-ziper-frante',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: true,
        rating: 4.9,
        rating_count: 54,
        sizes: ['P', 'M', 'G'],
        colors: ['Preto'],
        composition: '74% Poliamida, 26% Elastano com proteção UV50+ e alta compressão',
        description:
          'Reconhecida por unir inovação, estilo sofisticado e alta performance. Legging com zíper frontal personalizado e cós alto anatômico que garante firmeza e zero transparência.',
        images_urls: [
          'https://altogiro.com.br/cdn/shop/files/121305-C0049-1.jpg?v=1737559002&width=1000',
        ],
      },
      {
        name: 'Legging Cós Canelado Alto Giro Marsala',
        slug: 'legging-cos-canelado-alto-giro-marsala',
        category: 'leggings',
        brand: 'Alto Giro',
        external_price: 359.9,
        compare_at_price: 359.9,
        price: 287.92,
        external_site: 'Alto Giro Loja Oficial',
        external_url:
          'https://altogiro.com.br/en-en/collections/legging-fitness/products/legging-cos-canelado-alto-giro',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 36,
        sizes: ['P', 'M', 'G'],
        colors: ['Vermelho Marsala'],
        composition: 'Poliamida premium canelada de alta densidade',
        description:
          'Estilo sofisticado e alta performance para esporte e casual. Cós alto texturizado com suporte abdominal e toque sedoso.',
        images_urls: [
          'https://altogiro.com.br/cdn/shop/files/121314-C6172-1.jpg?crop=region&crop_height=2482&crop_left=192&crop_top=0&crop_width=1662&v=1782247380&width=1000',
        ],
      },
      {
        name: 'Legging Elástico Personalizado Alto Giro Verde Cálido',
        slug: 'legging-elastico-personalizado-alto-giro-verde-calido',
        category: 'leggings',
        brand: 'Alto Giro',
        external_price: 359.9,
        compare_at_price: 359.9,
        price: 287.92,
        external_site: 'Alto Giro Loja Oficial',
        external_url:
          'https://altogiro.com.br/en-en/collections/legging-fitness/products/legging-elastico-personalizado-alto-giro-19',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.7,
        rating_count: 29,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Verde Cálido'],
        composition: '76% Poliamida, 24% Elastano com tecnologia Lycra Adaptiv',
        description:
          'Peça voltada tanto para o esporte quanto para o uso casual. Elástico personalizado que não escorrega e alta cobertura anti-transparência.',
        images_urls: [
          'https://altogiro.com.br/cdn/shop/files/2611307-C6043-1.jpg?crop=region&crop_height=2482&crop_left=192&crop_top=0&crop_width=1662&v=1769603978&width=1000',
        ],
      },
      {
        name: 'Legging Essentials Alto Giro Azul Céu',
        slug: 'legging-essentials-alto-giro-azul-ceu',
        category: 'leggings',
        brand: 'Alto Giro',
        external_price: 298.9,
        compare_at_price: 298.9,
        price: 239.12,
        external_site: 'Alto Giro Loja Oficial',
        external_url:
          'https://altogiro.com.br/en-en/collections/legging-fitness/products/legging-essential-1',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 42,
        sizes: ['PP', 'P', 'M', 'G'],
        colors: ['Azul Céu'],
        composition: 'Poliamida biodegradable com proteção UV50+',
        description:
          'Inovação e conforto térmico da Alto Giro em tom azul suave, desenvolvida para flexibilidade e treinos em dias quentes.',
        images_urls: [
          'https://altogiro.com.br/cdn/shop/files/2631309-C0454-1.jpg?crop=region&crop_height=2482&crop_left=192&crop_top=0&crop_width=1662&v=1782310981&width=1000',
        ],
      },
      {
        name: 'Legging Recortes Shine Alto Giro',
        slug: 'legging-recortes-shine-alto-giro',
        category: 'leggings',
        brand: 'Alto Giro',
        external_price: 349.9,
        compare_at_price: 349.9,
        price: 279.92,
        external_site: 'Alto Giro Loja Oficial',
        external_url:
          'https://altogiro.com.br/en-en/collections/legging-fitness/products/legging-recortes-shine-5',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 31,
        sizes: ['P', 'M', 'G'],
        colors: ['Preto / Brilho Acetinado'],
        composition: 'Poliamida brilhante acetinada com toque frio',
        description:
          'Design sofisticado com recortes anatômicos que valorizam as curvas femininas e oferecem ajuste preciso.',
        images_urls: [
          'https://altogiro.com.br/cdn/shop/files/2531305-C6075-1.jpg?crop=region&crop_height=2482&crop_left=192&crop_top=0&crop_width=1662&v=1766514908&width=1000',
        ],
      },
      {
        name: 'Legging Eterna Cós Alto Anticelulite Alto Giro Azul Noturno',
        slug: 'legging-eterna-cos-alto-anticelulite-alto-giro-azul-noturno',
        category: 'leggings',
        brand: 'Alto Giro',
        external_price: 349.9,
        compare_at_price: 349.9,
        price: 279.92,
        external_site: 'Alto Giro Loja Oficial',
        external_url:
          'https://altogiro.com.br/en-en/collections/legging-fitness/products/legging-eterna-anticelulite-cos-alto-2',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: true,
        rating: 5.0,
        rating_count: 67,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Azul Noturno'],
        composition: 'Fio inteligente Emana com minerais bioativos anticelulite',
        description:
          'Tecnologia Emana de alta performance que estimula a microcirculação e reduz a fadiga muscular.',
        images_urls: [
          'https://altogiro.com.br/cdn/shop/files/2631305-C6248-1.jpg?crop=region&crop_height=2482&crop_left=192&crop_top=0&crop_width=1662&v=1782656534&width=1000',
        ],
      },
      {
        name: 'Bermuda 2 em 1 Masculina Alto Giro Preto',
        slug: 'bermuda-2-em-1-masculina-alto-giro-preto',
        category: 'shorts',
        brand: 'Alto Giro',
        external_price: 394.9,
        compare_at_price: 394.9,
        price: 315.92,
        external_site: 'Alto Giro Loja Oficial',
        external_url: 'https://altogiro.com.br/en-en/products/bermuda-2-em-1-masculina-preto',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 28,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto'],
        composition:
          'Short interno compressivo em poliamida e bermuda externa ultraleve 4-way stretch',
        description:
          'Peça masculina de alta tecnologia da Alto Giro com short de compressão interno antiassadura e tecido externo respirável.',
        images_urls: [
          'https://altogiro.com.br/cdn/shop/files/2410101-C0049-1.jpg?crop=region&crop_height=2482&crop_left=192&crop_top=0&crop_width=1662&v=1766519917&width=1000',
        ],
      },
      {
        name: 'Bermuda 5 Pro Alto Giro Preto',
        slug: 'bermuda-5-pro-alto-giro-preto',
        category: 'shorts',
        brand: 'Alto Giro',
        external_price: 379.9,
        compare_at_price: 379.9,
        price: 303.92,
        external_site: 'Alto Giro Loja Oficial',
        external_url: 'https://altogiro.com.br/en-en/products/bermuda-5-pro-6',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 45,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto'],
        composition: 'Poliamida com elastano de alta densidade e bolso funcional',
        description:
          'Bermuda ciclista de 5 polegadas para corrida e cross-training, com cós duplo estruturado e bolso lateral para celular.',
        images_urls: [
          'https://altogiro.com.br/cdn/shop/files/2611105-C0049-1.jpg?crop=region&crop_height=2482&crop_left=192&crop_top=0&crop_width=1662&v=1774013613&width=1000',
        ],
      },
      {
        name: 'Bermuda 5 Pro Alto Giro Rosa Aurora',
        slug: 'bermuda-5-pro-alto-giro-rosa-aurora',
        category: 'shorts',
        brand: 'Alto Giro',
        external_price: 379.9,
        compare_at_price: 379.9,
        price: 303.92,
        external_site: 'Alto Giro Loja Oficial',
        external_url: 'https://altogiro.com.br/en-en/products/bermuda-5-pro-8',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.7,
        rating_count: 33,
        sizes: ['P', 'M', 'G'],
        colors: ['Rosa Aurora'],
        composition: 'Poliamida toque aveludado com secagem rápida Quick Dry',
        description:
          'Modelagem perfeita que une alta performance com delicadeza visual em tom Rosa Aurora sofisticado.',
        images_urls: [
          'https://altogiro.com.br/cdn/shop/files/2611105-C6148-1.jpg?crop=region&crop_height=2482&crop_left=192&crop_top=0&crop_width=1662&v=1769603691&width=1000',
        ],
      },
      {
        name: 'Bermuda Detalhe Elástico Cós Alto Giro Bege Frio',
        slug: 'bermuda-detalhe-elastico-cos-alto-giro-bege-frio',
        category: 'shorts',
        brand: 'Alto Giro',
        external_price: 238.9,
        compare_at_price: 238.9,
        price: 191.12,
        external_site: 'Alto Giro Loja Oficial',
        external_url: 'https://altogiro.com.br/en-en/products/bermuda-detalhe-elastico-cos',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.6,
        rating_count: 21,
        sizes: ['P', 'M', 'G'],
        colors: ['Bege Frio'],
        composition: 'Poliamida premium com cós esportivo contrastante',
        description:
          'Bermuda casual chic para o esporte e pós-treino com elástico contrastante no cós e toque leve.',
        images_urls: [
          'https://altogiro.com.br/cdn/shop/files/2618130-C6140-1.jpg?crop=region&crop_height=2482&crop_left=192&crop_top=0&crop_width=1662&v=1770042088&width=1000',
        ],
      },
      {
        name: 'Bolsa Alça Dupla Esportiva Alto Giro',
        slug: 'bolsa-alca-dupla-esportiva-alto-giro',
        category: 'acessorios',
        brand: 'Alto Giro',
        external_price: 329.9,
        compare_at_price: 329.9,
        price: 263.92,
        external_site: 'Alto Giro Loja Oficial',
        external_url: 'https://altogiro.com.br/products/bolsa-alca-dupla',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: true,
        rating: 4.9,
        rating_count: 48,
        sizes: ['Tamanho Único (25L)'],
        colors: ['Preto / Bege'],
        composition: 'Nylon reforçado impermeabilizado com ferragens metálicas',
        description:
          'Bolsa esportiva prática com alça de ombro e de mão, acabamento entrelaçado sofisticado e divisória interna.',
        images_urls: [
          'https://img.usecurling.com/p/600/600?q=alto%20giro%20duffel%20bag%20fitness&color=black',
        ],
      },

      // ==========================================
      // 2. HONEY BE (11 produtos - 20% OFF)
      // "Famosa pela grande variedade de conjuntos, leggings e tecnologias de compressão com excelente custo-benefício."
      // ==========================================
      {
        name: 'Calça Legging Poliamida Básico Cintura Alta Rosa Honey Be',
        slug: 'calca-legging-poliamida-basico-cintura-alta-rosa-honey-be',
        category: 'leggings',
        brand: 'Honey Be',
        external_price: 89.94,
        compare_at_price: 149.9,
        price: 71.95,
        external_site: 'Honey Be Loja Oficial',
        external_url:
          'https://honeybe.com.br/products/calca-legging-poliamida-corte-basico-cintura-alta-rosa-lg2409',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: true,
        rating: 4.9,
        rating_count: 145,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Rosa'],
        composition:
          '80% Poliamida, 10% Microfibra Poliéster, 10% Elastano com tecnologia sem costura (seamless)',
        description:
          'Famosa pela grande variedade de conjuntos, leggings e tecnologias de compressão com excelente custo-benefício. Cós super largo de 11cm que não enrola.',
        images_urls: ['https://honeybe.com.br/cdn/shop/files/6L4A8365.jpg?v=1765976426&width=1000'],
      },
      {
        name: 'Calça Legging Poliamida Cintura Alta Azul Honey Be',
        slug: 'calca-legging-poliamida-cintura-alta-azul-honey-be',
        category: 'leggings',
        brand: 'Honey Be',
        external_price: 89.94,
        compare_at_price: 149.9,
        price: 71.95,
        external_site: 'Honey Be Loja Oficial',
        external_url:
          'https://honeybe.com.br/products/calca-legging-poliamida-corte-basico-cintura-alta-azul-lg2408',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 98,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Azul Marinho'],
        composition: 'Poliamida seamless com elasticidade multidirecional',
        description:
          'Compressão e conforto sem costuras laterais com alta respirabilidade para agachamentos pesados.',
        images_urls: ['https://honeybe.com.br/cdn/shop/files/6L4A8372.jpg?v=1771878698&width=1000'],
      },
      {
        name: 'Legging Fitness Básica Preta Honey Be LG2301',
        slug: 'legging-fitness-basica-preta-honey-be-lg2301',
        category: 'leggings',
        brand: 'Honey Be',
        external_price: 79.9,
        compare_at_price: 109.9,
        price: 63.92,
        external_site: 'Honey Be Loja Oficial',
        external_url:
          'https://honeybe.com.br/products/legging-fitness-basica-preta-lg2301-690cf43d214ea',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.7,
        rating_count: 210,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto'],
        composition: 'Suplex de alta densidade zero transparência',
        description:
          'O clássico mais vendido da Honey Be: tecido firme, durável e com modelagem que se ajusta anatomicamente.',
        images_urls: [
          'https://honeybe.com.br/cdn/shop/files/LeggingFitnessBasicaPretaLG2301_2.jpg?v=1751030285&width=1000',
        ],
      },
      {
        name: 'Legging Fitness Seamless Cappuccino Canelada Honey Be',
        slug: 'legging-fitness-seamless-cappuccino-canelada-honey-be',
        category: 'leggings',
        brand: 'Honey Be',
        external_price: 99.9,
        compare_at_price: 139.9,
        price: 79.92,
        external_site: 'Honey Be Loja Oficial',
        external_url:
          'https://honeybe.com.br/products/legging-fitness-seamless-cappuccino-canelada-lg2285-690cf5b9d4c95',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 85,
        sizes: ['P', 'M', 'G'],
        colors: ['Cappuccino'],
        composition: 'Poliamida canelada sem costura toque de segunda pele',
        description:
          'Tecnologia seamless em cor tendência cappuccino com compressão média e efeito modelador.',
        images_urls: [
          'https://img.usecurling.com/p/600/750?q=honey%20be%20legging%20seamless%20cappuccino&color=brown',
        ],
      },
      {
        name: 'Legging Fitness Energy Fúcsia Honey Be',
        slug: 'legging-fitness-energy-fucsia-honey-be',
        category: 'leggings',
        brand: 'Honey Be',
        external_price: 89.9,
        compare_at_price: 129.9,
        price: 71.92,
        external_site: 'Honey Be Loja Oficial',
        external_url:
          'https://honeybe.com.br/products/legging-fitness-energy-basica-fucsia-lg2296-690cf4c050e3a',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 67,
        sizes: ['P', 'M', 'G'],
        colors: ['Fúcsia Vibrante'],
        composition: 'Poliamida com elastano UV50+ e proteção antimicrobiana',
        description:
          'Cor enérgica com tecnologia que auxilia na recuperação muscular através de compressão graduada.',
        images_urls: [
          'https://img.usecurling.com/p/600/750?q=honey%20be%20legging%20fuchsia%20fitness&color=pink',
        ],
      },
      {
        name: 'Short Fitness Básico Preto Honey Be SH742',
        slug: 'short-fitness-basico-preto-honey-be-sh742',
        category: 'shorts',
        brand: 'Honey Be',
        external_price: 49.9,
        compare_at_price: 69.9,
        price: 39.92,
        external_site: 'Honey Be Loja Oficial',
        external_url:
          'https://honeybe.com.br/products/short-fitness-preto-basico-sh742-691370b8ce79a',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.7,
        rating_count: 178,
        sizes: ['P', 'M', 'G'],
        colors: ['Preto'],
        composition: 'Poliamida elástica com toque gelado',
        description:
          'Shortinho de treino com comprimento confortável que não sobe durante passadas e agachamentos.',
        images_urls: [
          'https://honeybe.com.br/cdn/shop/files/ShortFitnessPretoBasicoSH742.jpg?v=1752239465&width=1000',
        ],
      },
      {
        name: 'Camiseta Básica Lisa Off-White Honey Be CT853',
        slug: 'camiseta-basica-lisa-off-white-honey-be-ct853',
        category: 'camisetas',
        brand: 'Honey Be',
        external_price: 29.9,
        compare_at_price: 49.9,
        price: 23.92,
        external_site: 'Honey Be Loja Oficial',
        external_url:
          'https://honeybe.com.br/products/camiseta-basica-lisa-off-white-ct853-690cf1a0d147d',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.6,
        rating_count: 112,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Off-White'],
        composition: 'Viscose com elastano leve e respirável',
        description:
          'Camiseta fitness curinga para sobreposição sobre tops esportivos, toque super leve e fresco.',
        images_urls: [
          'https://honeybe.com.br/cdn/shop/files/honey20400.jpg?v=1752176531&width=1000',
        ],
      },
      {
        name: 'Regata Feminina Canelada Honey Be Preta',
        slug: 'regata-feminina-canelada-honey-be-preta',
        category: 'regatas',
        brand: 'Honey Be',
        external_price: 129.0,
        compare_at_price: 149.0,
        price: 103.2,
        external_site: 'Honey Be Loja Oficial',
        external_url:
          'https://honeybe.com.br/products/regata-viscose-feminina-canelada-elastano-preta-1315e7520-1',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 73,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto'],
        composition: 'Malha canelada premium com elastano',
        description:
          'Regata esportiva e casual de caimento ajustado com excelente conforto térmico.',
        images_urls: [
          'https://honeybe.com.br/cdn/shop/files/13201.1.GG_1.jpg?v=1760623150&width=1000',
        ],
      },
      {
        name: 'Top Fitness Duplo Sustentação Preto Honey Be TP1846',
        slug: 'top-fitness-duplo-sustentacao-preto-honey-be-tp1846',
        category: 'camisetas',
        brand: 'Honey Be',
        external_price: 129.9,
        compare_at_price: 169.0,
        price: 103.92,
        external_site: 'Honey Be Loja Oficial',
        external_url:
          'https://honeybe.com.br/products/top-fitess-assimetrico-tecido-duplo-premium-bojo-embutido-preto-tp1846',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: true,
        rating: 4.9,
        rating_count: 89,
        sizes: ['P', 'M', 'G'],
        colors: ['Preto'],
        composition: 'Tecido duplo de alta sustentação com bojo embutido',
        description:
          'Top fitness estruturado que garante suporte firme para corridas e treinos de alto impacto.',
        images_urls: [
          'https://honeybe.com.br/cdn/shop/files/71f9a41a-fa5f-49cd-a010-6ca1ca7ed81a.jpg?v=1765982444&width=1000',
        ],
      },
      {
        name: 'Macaquinho Fitness Texturizado Honey Be Lilás MC394',
        slug: 'macaquinho-fitness-texturizado-honey-be-lilas-mc394',
        category: 'leggings',
        brand: 'Honey Be',
        external_price: 129.9,
        compare_at_price: 199.0,
        price: 103.92,
        external_site: 'Honey Be Loja Oficial',
        external_url:
          'https://honeybe.com.br/products/macaquinho-fintess-premium-tecido-texturizado-lilas-mc394',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 57,
        sizes: ['P', 'M', 'G'],
        colors: ['Lilás Suave'],
        composition: 'Poliamida texturizada de alta cobertura com zero transparência',
        description:
          'Conjunto inteiro macaquinho que esculpe a silhueta e oferece total liberdade sem ajustes na cintura.',
        images_urls: [
          'https://honeybe.com.br/cdn/shop/files/4cadb130-ebf2-4ecc-9de6-1cc2161d4cd7.jpg?v=1765992639&width=1000',
        ],
      },
      {
        name: 'Boné Esportivo Sempre Mantendo o Foco Honey Be',
        slug: 'bone-esportivo-sempre-mantendo-o-foco-honey-be',
        category: 'acessorios',
        brand: 'Honey Be',
        external_price: 39.9,
        compare_at_price: 59.9,
        price: 31.92,
        external_site: 'Honey Be Loja Oficial',
        external_url:
          'https://honeybe.com.br/products/bone-preto-sempre-mantendo-o-foco-bn025-690cf058bc880',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.7,
        rating_count: 94,
        sizes: ['Tamanho Único Ajustável'],
        colors: ['Preto'],
        composition: 'Tecido sarja 100% algodão com fecho ajustável e fita absorvente interna',
        description:
          'Boné fitness Honey Be com bordado frontal e aba curva protetora solar para treinos ao ar livre.',
        images_urls: [
          'https://honeybe.com.br/cdn/shop/files/BonePretoSempreMantendooFoco.jpg?v=1752585010&width=1000',
        ],
      },

      // ==========================================
      // 3. DLK (11 produtos - 20% OFF)
      // "Marca com fabricação própria especializada em moda fitness feminina, masculina e infantil, destacando-se pela durabilidade e variedade de modelos."
      // ==========================================
      {
        name: 'Legging Cós Transpassado Athletic DLK Marrom',
        slug: 'legging-cos-transpassado-athletic-dlk-marrom',
        category: 'leggings',
        brand: 'DLK',
        external_price: 141.99,
        compare_at_price: 141.99,
        price: 113.59,
        external_site: 'DLK Moda Fitness Loja Oficial',
        external_url:
          'https://dlk.com.br/products/legging-fitness-feminina-com-cos-transpassado-e-elastico-athletic-dlk-marrom',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: true,
        rating: 4.9,
        rating_count: 88,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Marrom'],
        composition: 'Poliamida com elastano de alta densidade e costura reforçada',
        description:
          'Marca com fabricação própria especializada em moda fitness. O cós transpassado em V afina a cintura e proporciona encaixe anatômico seguro.',
        images_urls: ['https://dlk.com.br/cdn/shop/files/FT9221_1.jpg?v=1790166400&width=1000'],
      },
      {
        name: 'Legging Bolsos e Elástico Athletic DLK Marrom',
        slug: 'legging-bolsos-e-elastico-athletic-dlk-marrom',
        category: 'leggings',
        brand: 'DLK',
        external_price: 164.99,
        compare_at_price: 164.99,
        price: 131.99,
        external_site: 'DLK Moda Fitness Loja Oficial',
        external_url:
          'https://dlk.com.br/products/legging-fitness-feminina-com-bolsos-e-elastico-athletic-dlk-marrom',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 65,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Marrom Café'],
        composition: 'Poliamida premium de média compressão com proteção UV',
        description:
          'Destacando-se pela durabilidade e variedade de modelos. Bolsos laterais fundos para celular e cós com elástico que não escorrega.',
        images_urls: ['https://dlk.com.br/cdn/shop/files/FT9225_1.jpg?v=1790166462&width=1000'],
      },
      {
        name: 'Legging Bolsos e Elástico Athletic DLK Preto',
        slug: 'legging-bolsos-e-elastico-athletic-dlk-preto',
        category: 'leggings',
        brand: 'DLK',
        external_price: 164.99,
        compare_at_price: 164.99,
        price: 131.99,
        external_site: 'DLK Moda Fitness Loja Oficial',
        external_url:
          'https://dlk.com.br/products/legging-fitness-feminina-com-bolsos-e-elastico-athletic-dlk-preto',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 142,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto'],
        composition: 'Poliamida fosca com alta taxa de retorno elástico',
        description:
          'Zero transparência no agachamento. Peça campeã de vendas com fabricação própria nacional.',
        images_urls: ['https://dlk.com.br/cdn/shop/files/FT9222_1.jpg?v=1787148814&width=1000'],
      },
      {
        name: 'Legging Cós Transpassado Athletic DLK Preto',
        slug: 'legging-cos-transpassado-athletic-dlk-preto',
        category: 'leggings',
        brand: 'DLK',
        external_price: 141.99,
        compare_at_price: 141.99,
        price: 113.59,
        external_site: 'DLK Moda Fitness Loja Oficial',
        external_url:
          'https://dlk.com.br/products/legging-fitness-feminina-com-cos-transpassado-e-elastico-athletic-dlk-preto',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 115,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto'],
        composition: 'Poliamida com elastano e efeito empina bumbum sutil',
        description:
          'Cós em V de sustentação anatômica com toque sedoso e frescor contínuo durante o exercício.',
        images_urls: ['https://dlk.com.br/cdn/shop/files/FT9217_1.jpg?v=1790075715&width=1000'],
      },
      {
        name: 'Legging Bolsos e Elástico Athletic DLK Azul Marinho',
        slug: 'legging-bolsos-e-elastico-athletic-dlk-azul-marinho',
        category: 'leggings',
        brand: 'DLK',
        external_price: 164.99,
        compare_at_price: 164.99,
        price: 131.99,
        external_site: 'DLK Moda Fitness Loja Oficial',
        external_url:
          'https://dlk.com.br/products/legging-fitness-feminina-com-bolsos-e-elastico-athletic-dlk-azul-marinho',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.7,
        rating_count: 63,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Azul Marinho'],
        composition: 'Poliamida tecnológica com acabamento dry e bolsos funcionais',
        description:
          'Tonalidade azul marinho elegante com alta durabilidade de lavagem e secagem express.',
        images_urls: ['https://dlk.com.br/cdn/shop/files/FT9224_1.jpg?v=1787061297&width=1000'],
      },
      {
        name: 'Legging Cós Transpassado Athletic DLK Azul Marinho',
        slug: 'legging-cos-transpassado-athletic-dlk-azul-marinho',
        category: 'leggings',
        brand: 'DLK',
        external_price: 141.99,
        compare_at_price: 141.99,
        price: 113.59,
        external_site: 'DLK Moda Fitness Loja Oficial',
        external_url:
          'https://dlk.com.br/products/legging-fitness-feminina-com-cos-transpassado-e-elastico-athletic-dlk-azul-marinho',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 51,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Azul Marinho'],
        composition: 'Poliamida respirável antissuor com cós anatômico',
        description: 'Modelagem que abraça a cintura sem apertar e costuras lisas anti-atrito.',
        images_urls: ['https://dlk.com.br/cdn/shop/files/FT9219_1.jpg?v=1787061316&width=1000'],
      },
      {
        name: 'Legging Cós Transpassado Athletic DLK Roxo',
        slug: 'legging-cos-transpassado-athletic-dlk-roxo',
        category: 'leggings',
        brand: 'DLK',
        external_price: 141.99,
        compare_at_price: 141.99,
        price: 113.59,
        external_site: 'DLK Moda Fitness Loja Oficial',
        external_url:
          'https://dlk.com.br/products/legging-fitness-feminina-com-cos-transpassado-e-elastico-athletic-dlk-roxo',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 44,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Roxo'],
        composition: 'Poliamida acetinada resistente a atritos e lavagens',
        description:
          'Cor roxa marcante com durabilidade insuperável garantida pela fabricação própria DLK.',
        images_urls: ['https://dlk.com.br/cdn/shop/files/FT9218_1.jpg?v=1787061310&width=1000'],
      },
      {
        name: 'Legging Bolsos e Elástico Athletic DLK Roxo',
        slug: 'legging-bolsos-e-elastico-athletic-dlk-roxo',
        category: 'leggings',
        brand: 'DLK',
        external_price: 164.99,
        compare_at_price: 164.99,
        price: 131.99,
        external_site: 'DLK Moda Fitness Loja Oficial',
        external_url:
          'https://dlk.com.br/products/legging-fitness-feminina-com-bolsos-e-elastico-athletic-dlk-roxo',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 39,
        sizes: ['P', 'M', 'G'],
        colors: ['Roxo Intenso'],
        composition: 'Poliamida 300g com elastano e proteção solar UV',
        description:
          'Praticidade com bolsos laterais espaçosos e sustentação firme para crossfit e musculação.',
        images_urls: ['https://dlk.com.br/cdn/shop/files/FT9223_1.jpg?v=1787061290&width=1000'],
      },
      {
        name: 'Short Fitness Feminino Soul DLK Azul Marinho',
        slug: 'short-fitness-feminino-soul-dlk-azul-marinho',
        category: 'shorts',
        brand: 'DLK',
        external_price: 99.9,
        compare_at_price: 99.9,
        price: 79.92,
        external_site: 'DLK Moda Fitness Loja Oficial',
        external_url: 'https://dlk.com.br/products/short-fitness-feminino-soul-dlk-azul-marinho',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 59,
        sizes: ['P', 'M', 'G'],
        colors: ['Azul Marinho'],
        composition: 'Poliamida com elastano e cós duplo',
        description:
          'Short confortável para bike, yoga, musculação ou esteira com elasticidade nos 4 sentidos.',
        images_urls: [
          'https://img.usecurling.com/p/600/700?q=dlk%20biker%20shorts%20navy%20blue&color=navy',
        ],
      },
      {
        name: 'Calça Flare Fitness Bailarina DLK Preta',
        slug: 'calca-flare-fitness-bailarina-dlk-preta',
        category: 'calcas',
        brand: 'DLK',
        external_price: 139.9,
        compare_at_price: 139.9,
        price: 111.92,
        external_site: 'DLK Moda Fitness Loja Oficial',
        external_url: 'https://dlk.com.br/collections/calcas_flare',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: true,
        rating: 4.9,
        rating_count: 120,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto'],
        composition: 'Poliamida encorpada sem transparência',
        description:
          'A clássica calça bailarina flare que alonga as pernas e transita com perfeição do treino ao dia a dia.',
        images_urls: [
          'https://dlk.com.br/cdn/shop/collections/07._calca_flare.jpg?v=1779357257&width=1000',
        ],
      },
      {
        name: 'Top Strappy Duplo Sustentação DLK Preto',
        slug: 'top-strappy-duplo-sustentacao-dlk-preto',
        category: 'camisetas',
        brand: 'DLK',
        external_price: 89.9,
        compare_at_price: 89.9,
        price: 71.92,
        external_site: 'DLK Moda Fitness Loja Oficial',
        external_url: 'https://dlk.com.br/collections/tops',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.7,
        rating_count: 81,
        sizes: ['P', 'M', 'G'],
        colors: ['Preto'],
        composition: 'Poliamida com tiras reforçadas nas costas e elástico embutido no cós',
        description:
          'Design moderno de tiras com suporte firme para treino de hipertrofia e corrida.',
        images_urls: [
          'https://img.usecurling.com/p/600/600?q=dlk%20sports%20bra%20strappy%20black&color=black',
        ],
      },

      // ==========================================
      // 4. LIVE! OFICIAL (11 produtos - 20% OFF)
      // "Grife nacional de destaque com foco em design sofisticado, coleções modernas e forte presença no estilo athleisure (esporte aliado à moda urbana)."
      // ==========================================
      {
        name: 'Legging LIVE! Signature Athleisure Noir Black',
        slug: 'legging-live-signature-athleisure-noir-black',
        category: 'leggings',
        brand: 'Live! Oficial',
        external_price: 349.9,
        compare_at_price: 349.9,
        price: 279.92,
        external_site: 'LIVE! Loja Oficial',
        external_url: 'https://www.liveoficial.com.br/moda-fitness/calcas-e-leggings/leggings',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: true,
        rating: 5.0,
        rating_count: 92,
        sizes: ['PP', 'P', 'M', 'G', 'GG'],
        colors: ['Noir Black'],
        composition: 'Poliamida biodegradable Amni Soul Eco com proteção UV50+',
        description:
          'Grife nacional de destaque com foco em design sofisticado, coleções modernas e forte presença no estilo athleisure (esporte aliado à moda urbana). Modelagem perfeita e toque gelado.',
        images_urls: [
          'https://imagens.liveoficial.com.br/product/750x1125/518428_46740_00PT01_2.jpg',
        ],
      },
      {
        name: 'Top LIVE! Essential Fitwear Branco Neve',
        slug: 'top-live-essential-fitwear-branco-neve',
        category: 'camisetas',
        brand: 'Live! Oficial',
        external_price: 199.9,
        compare_at_price: 199.9,
        price: 159.92,
        external_site: 'LIVE! Loja Oficial',
        external_url: 'https://www.liveoficial.com.br/moda-fitness/tops',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 64,
        sizes: ['P', 'M', 'G'],
        colors: ['Branco Neve'],
        composition: 'Tecido duplo com bojo removível e tecnologia Quick Dry',
        description:
          'Design sofisticado athleisure da LIVE! Oficial, aliando conforto no treino de alta intensidade com elegância urbana.',
        images_urls: [
          'https://imagens.liveoficial.com.br/product/750x1125/518429_46740_00BC01_1.jpg',
        ],
      },
      {
        name: 'Shorts LIVE! Run Motion Noir Black',
        slug: 'shorts-live-run-motion-noir-black',
        category: 'shorts',
        brand: 'Live! Oficial',
        external_price: 249.9,
        compare_at_price: 249.9,
        price: 199.92,
        external_site: 'LIVE! Loja Oficial',
        external_url: 'https://www.liveoficial.com.br/moda-fitness/shorts-e-bermudas',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 49,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Noir Black'],
        composition: 'Microfibra técnica ultra leve com forro interno respirável',
        description:
          'Shorts de corrida e academia com fendas laterais para amplitude irrestrita de movimentos.',
        images_urls: [
          'https://imagens.liveoficial.com.br/product/750x1125/514417_46689_00PT01_2.jpg',
        ],
      },
      {
        name: 'Camiseta LIVE! Urban Athleisure Cocoa Brown',
        slug: 'camiseta-live-urban-athleisure-cocoa-brown',
        category: 'camisetas',
        brand: 'Live! Oficial',
        external_price: 299.9,
        compare_at_price: 299.9,
        price: 239.92,
        external_site: 'LIVE! Loja Oficial',
        external_url:
          'https://www.liveoficial.com.br/camiseta-casual-comfy-men-cocoa-brown-P166700MR76/p',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 38,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Cocoa Brown'],
        composition: 'Algodão Pima peruano com poliamida e elastano',
        description:
          'Transição perfeita entre esporte e moda urbana, com caimento fluido e acabamentos termo-colados.',
        images_urls: [
          'https://imagens.liveoficial.com.br/product/750x1125/511904_P1667_00MR76_2.jpg',
        ],
      },
      {
        name: 'Regata LIVE! Breeze High Neck Mountain Grey',
        slug: 'regata-live-breeze-high-neck-mountain-grey',
        category: 'regatas',
        brand: 'Live! Oficial',
        external_price: 199.9,
        compare_at_price: 199.9,
        price: 159.92,
        external_site: 'LIVE! Loja Oficial',
        external_url: 'https://www.liveoficial.com.br/moda-fitness/blusas-e-regatas/regatas',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 32,
        sizes: ['P', 'M', 'G'],
        colors: ['Mountain Grey'],
        composition: 'Tecido Breeze microperfurado antiodor',
        description:
          'Gola alta esportiva com recortes anatômicos para um visual athleisure imponente.',
        images_urls: [
          'https://imagens.liveoficial.com.br/product/750x1125/512007_46681_00CZ85_1.jpg',
        ],
      },
      {
        name: 'Calça Jogger LIVE! Tech Flex Noir Black',
        slug: 'calca-jogger-live-tech-flex-noir-black',
        category: 'calcas',
        brand: 'Live! Oficial',
        external_price: 499.0,
        compare_at_price: 499.0,
        price: 399.2,
        external_site: 'LIVE! Loja Oficial',
        external_url: 'https://www.liveoficial.com.br/moda-fitness/calcas-e-leggings',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: true,
        rating: 5.0,
        rating_count: 41,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Noir Black'],
        composition: 'Poliamida encorpada 4-way stretch com punhos canelados e bolsos com zíper',
        description:
          'Calça jogger sofisticada para treinos e viagens, com cós em cordão e caimento alfaiataria esportiva.',
        images_urls: [
          'https://imagens.liveoficial.com.br/product/750x1125/529218_46675_00PT01_1.jpg',
        ],
      },
      {
        name: 'Jaqueta Corta-Vento LIVE! Wind Motion Preto',
        slug: 'jaqueta-corta-vento-live-wind-motion-preto',
        category: 'jaquetas',
        brand: 'Live! Oficial',
        external_price: 689.0,
        compare_at_price: 689.0,
        price: 551.2,
        external_site: 'LIVE! Loja Oficial',
        external_url: 'https://www.liveoficial.com.br/jaquetas',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 27,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Noir Black'],
        composition: 'Tecido corta-vento hidrorrepelente ultraleve',
        description:
          'Jaqueta técnica moderna com bolsos invisíveis e capuz anatômico para corridas e lifestyle urbano.',
        images_urls: [
          'https://imagens.liveoficial.com.br/product/750x1125/515525_46571_00PT01_1.jpg',
        ],
      },
      {
        name: 'Moletom Cropped LIVE! Minimal Rosa Quartz',
        slug: 'moletom-cropped-live-minimal-rosa-quartz',
        category: 'moletons',
        brand: 'Live! Oficial',
        external_price: 399.0,
        compare_at_price: 399.0,
        price: 319.2,
        external_site: 'LIVE! Loja Oficial',
        external_url: 'https://www.liveoficial.com.br/moletons',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 35,
        sizes: ['P', 'M', 'G'],
        colors: ['Rosa Quartz'],
        composition: 'Moletinho premium 100% algodão com toque de pêssego',
        description:
          'Modelagem cropped comfy da grife LIVE!, ideal para sobreposições pós-treino e passeios casuais.',
        images_urls: [
          'https://imagens.liveoficial.com.br/product/750x1125/518430_46740_00RS22_1.jpg',
        ],
      },
      {
        name: 'Legging LIVE! Glossy Sculpt Blue Ink',
        slug: 'legging-live-glossy-sculpt-blue-ink',
        category: 'leggings',
        brand: 'Live! Oficial',
        external_price: 389.0,
        compare_at_price: 389.0,
        price: 311.2,
        external_site: 'LIVE! Loja Oficial',
        external_url: 'https://www.liveoficial.com.br/moda-fitness/calcas-e-leggings',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 48,
        sizes: ['P', 'M', 'G'],
        colors: ['Blue Ink'],
        composition: 'Poliamida brilhosa com elastano e compressão graduada',
        description:
          'Efeito brilhoso sutil que confere status de alta costura à peça esportiva, mantendo sustentação impecável.',
        images_urls: [
          'https://imagens.liveoficial.com.br/product/750x1125/511923_46675_0AZ218_2.jpg',
        ],
      },
      {
        name: 'Bermuda Ciclista LIVE! Comfort Eclipse',
        slug: 'bermuda-ciclista-live-comfort-eclipse',
        category: 'shorts',
        brand: 'Live! Oficial',
        external_price: 279.0,
        compare_at_price: 279.0,
        price: 223.2,
        external_site: 'LIVE! Loja Oficial',
        external_url: 'https://www.liveoficial.com.br/moda-fitness/shorts-e-bermudas',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.7,
        rating_count: 36,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Eclipse'],
        composition: 'Poliamida biodegradable com compressão suave',
        description:
          'Bermuda ciclista confortável para treinos em estúdio e passeios descontraídos.',
        images_urls: [
          'https://imagens.liveoficial.com.br/product/750x1125/514507_P8111_00PT02_2.jpg',
        ],
      },
      {
        name: 'Bolsa LIVE! Gym Tote Tech Porcelain',
        slug: 'bolsa-live-gym-tote-tech-porcelain',
        category: 'acessorios',
        brand: 'Live! Oficial',
        external_price: 599.0,
        compare_at_price: 599.0,
        price: 479.2,
        external_site: 'LIVE! Loja Oficial',
        external_url: 'https://www.liveoficial.com.br/acessorios/bolsas-e-mochilas',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 5.0,
        rating_count: 22,
        sizes: ['Tamanho Único (32L)'],
        colors: ['Porcelain'],
        composition:
          'Tecido sintético resistente a respingos com alças reforçadas e suporte para tapete de yoga',
        description:
          'Bolsa tote esportiva de alto padrão com suporte para mat de yoga e múltiplos compartimentos térmicos.',
        images_urls: [
          'https://imagens.liveoficial.com.br/product/750x1125/515162_IP103_00CZ85_1.jpg',
        ],
      },

      // ==========================================
      // 5. DE CORPO (11 produtos - 20% OFF)
      // "Conhecida pelos tecidos tecnológicos com toque gelado e proteção solar para atividades ao ar livre."
      // ==========================================
      {
        name: 'Camiseta De Corpo Ice Touch Manga Curta UV50+ Azul Glacial',
        slug: 'camiseta-de-corpo-ice-touch-manga-curta-uv50-azul-glacial',
        category: 'camisetas',
        brand: 'De Corpo',
        external_price: 159.9,
        compare_at_price: 159.9,
        price: 127.92,
        external_site: 'De Corpo Moda Fitness Oficial',
        external_url: 'https://www.decorpo.com.br/camisetas/ice-touch-uv50-azul',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: true,
        rating: 4.9,
        rating_count: 76,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Azul Glacial'],
        composition: '90% Poliamida Ice Touch, 10% Elastano com proteção solar permanente FPU 50+',
        description:
          'Conhecida pelos tecidos tecnológicos com toque gelado e proteção solar para atividades ao ar livre. Mantém a temperatura corporal amena mesmo sob sol escaldante.',
        images_urls: [
          'https://img.usecurling.com/p/600/750?q=fitness%20shirt%20ice%20blue%20cold%20touch&color=blue',
        ],
      },
      {
        name: 'Camiseta De Corpo Ice Touch Manga Longa Proteção Solar UV50+ Branca',
        slug: 'camiseta-de-corpo-ice-touch-manga-longa-protecao-solar-uv50-branca',
        category: 'camisetas',
        brand: 'De Corpo',
        external_price: 189.9,
        compare_at_price: 189.9,
        price: 151.92,
        external_site: 'De Corpo Moda Fitness Oficial',
        external_url: 'https://www.decorpo.com.br/camisetas/manga-longa-uv50-branca',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 94,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Branco'],
        composition:
          'Microfibra de poliamida com partículas minerais refrescantes e proteção UV50+',
        description:
          'Manga longa com orifício para o polegar para corridas ao ar livre e caminhadas na praia com total bloqueio solar.',
        images_urls: [
          'https://img.usecurling.com/p/600/750?q=long%20sleeve%20uv%20protective%20running%20shirt%20white&color=white',
        ],
      },
      {
        name: 'Regata De Corpo Toque Gelado Solar Marinho',
        slug: 'regata-de-corpo-toque-gelado-solar-marinho',
        category: 'regatas',
        brand: 'De Corpo',
        external_price: 139.9,
        compare_at_price: 139.9,
        price: 111.92,
        external_site: 'De Corpo Moda Fitness Oficial',
        external_url: 'https://www.decorpo.com.br/regatas/toque-gelado-marinho',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 53,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Azul Marinho'],
        composition: 'Poliamida respirável antissuor com toque gelado duradouro',
        description:
          'Corte cavado ergonômico que não retém umidade durante o treino sob altas temperaturas.',
        images_urls: [
          'https://img.usecurling.com/p/600/750?q=mens%20athletic%20tank%20top%20navy%20blue&color=navy',
        ],
      },
      {
        name: 'Legging De Corpo Solar Shield Cós Alto Verde Oliva',
        slug: 'legging-de-corpo-solar-shield-cos-alto-verde-oliva',
        category: 'leggings',
        brand: 'De Corpo',
        external_price: 249.9,
        compare_at_price: 249.9,
        price: 199.92,
        external_site: 'De Corpo Moda Fitness Oficial',
        external_url: 'https://www.decorpo.com.br/leggings/solar-shield-oliva',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: true,
        rating: 4.9,
        rating_count: 67,
        sizes: ['P', 'M', 'G'],
        colors: ['Verde Oliva'],
        composition: 'Poliamida compressiva Ice Tech com proteção UV50+',
        description:
          'Tecido de compressão uniforme com proteção solar e toque gelado imediato ao contato com a pele.',
        images_urls: [
          'https://img.usecurling.com/p/600/750?q=olive%20green%20fitness%20leggings%20clean&color=green',
        ],
      },
      {
        name: 'Legging De Corpo Proteção UV50+ Preta Básica',
        slug: 'legging-de-corpo-protecao-uv50-preta-basica',
        category: 'leggings',
        brand: 'De Corpo',
        external_price: 239.9,
        compare_at_price: 239.9,
        price: 191.92,
        external_site: 'De Corpo Moda Fitness Oficial',
        external_url: 'https://www.decorpo.com.br/leggings/uv50-preta',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 82,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto'],
        composition: 'Poliamida e elastano com tecnologia de dispersão de calor',
        description:
          'Sem transparência e com sensação de frescor contínuo para exercícios ao ar livre.',
        images_urls: [
          'https://img.usecurling.com/p/600/750?q=black%20athletic%20leggings%20cold%20fabric&color=black',
        ],
      },
      {
        name: 'Shorts Duplo Corrida De Corpo Toque Gelado Preto',
        slug: 'shorts-duplo-corrida-de-corpo-toque-gelado-preto',
        category: 'shorts',
        brand: 'De Corpo',
        external_price: 179.9,
        compare_at_price: 179.9,
        price: 143.92,
        external_site: 'De Corpo Moda Fitness Oficial',
        external_url: 'https://www.decorpo.com.br/shorts/duplo-corrida-preto',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 45,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Preto'],
        composition: 'Bermuda interna com toque gelado e camada externa fluida ultraleve',
        description: 'Evita assaduras e mantém as pernas frescas na esteira e corrida de rua.',
        images_urls: [
          'https://img.usecurling.com/p/600/700?q=mens%20running%20shorts%202in1%20black&color=black',
        ],
      },
      {
        name: 'Shorts Ciclista De Corpo Proteção Solar Lavanda',
        slug: 'shorts-ciclista-de-corpo-protecao-solar-lavanda',
        category: 'shorts',
        brand: 'De Corpo',
        external_price: 169.9,
        compare_at_price: 169.9,
        price: 135.92,
        external_site: 'De Corpo Moda Fitness Oficial',
        external_url: 'https://www.decorpo.com.br/shorts/ciclista-solar-lavanda',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.7,
        rating_count: 38,
        sizes: ['P', 'M', 'G'],
        colors: ['Lavanda'],
        composition: 'Poliamida Ice Touch com cós alto sem elástico compressivo',
        description:
          'Modelagem biker feminina suave em tom lavanda com bloqueio comprovado de 98% dos raios UV.',
        images_urls: [
          'https://img.usecurling.com/p/600/700?q=lavender%20biker%20shorts%20fitness&color=purple',
        ],
      },
      {
        name: 'Calça Jogger De Corpo Air Flow Cinza Chumbo',
        slug: 'calca-jogger-de-corpo-air-flow-cinza-chumbo',
        category: 'calcas',
        brand: 'De Corpo',
        external_price: 279.9,
        compare_at_price: 279.9,
        price: 223.92,
        external_site: 'De Corpo Moda Fitness Oficial',
        external_url: 'https://www.decorpo.com.br/calcas/jogger-air-flow-chumbo',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 51,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Cinza Chumbo'],
        composition: 'Tecido plano elástico respirável com tratamento hidrofóbico e proteção solar',
        description: 'Calça esportiva leve para aquecimentos ao ar livre e rotina fitness prática.',
        images_urls: [
          'https://img.usecurling.com/p/600/750?q=grey%20athletic%20jogger%20pants%20minimalist&color=grey',
        ],
      },
      {
        name: 'Jaqueta Corta-Vento De Corpo UV Ultraleve Grafite',
        slug: 'jaqueta-corta-vento-de-corpo-uv-ultraleve-grafite',
        category: 'jaquetas',
        brand: 'De Corpo',
        external_price: 319.9,
        compare_at_price: 319.9,
        price: 255.92,
        external_site: 'De Corpo Moda Fitness Oficial',
        external_url: 'https://www.decorpo.com.br/jaquetas/corta-vento-uv-grafite',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 36,
        sizes: ['P', 'M', 'G', 'GG'],
        colors: ['Grafite'],
        composition: 'Nylon ripstop microporoso com proteção solar UV50+',
        description:
          'Barreira contra o vento e o sol forte com aberturas de ventilação nas costas.',
        images_urls: [
          'https://img.usecurling.com/p/600/750?q=graphite%20windbreaker%20jacket%20running&color=grey',
        ],
      },
      {
        name: 'Viseira Esportiva De Corpo Proteção UV50+ Aba Curva',
        slug: 'viseira-esportiva-de-corpo-protecao-uv50-aba-curva',
        category: 'acessorios',
        brand: 'De Corpo',
        external_price: 89.9,
        compare_at_price: 89.9,
        price: 71.92,
        external_site: 'De Corpo Moda Fitness Oficial',
        external_url: 'https://www.decorpo.com.br/acessorios/viseira-uv50',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 61,
        sizes: ['Tamanho Único Ajustável'],
        colors: ['Branco / Preto'],
        composition:
          'Aba em EVA com forro atoalhado absorvente de suor e tecido com bloqueio solar',
        description:
          'Acessório indispensável para caminhadas, corridas e beach tennis mantendo a cabeça fresca.',
        images_urls: [
          'https://img.usecurling.com/p/600/600?q=white%20sports%20sun%20visor%20running&color=white',
        ],
      },
      {
        name: 'Manguito Esportivo De Corpo Ice Touch Par UV50+',
        slug: 'manguito-esportivo-de-corpo-ice-touch-par-uv50',
        category: 'acessorios',
        brand: 'De Corpo',
        external_price: 79.9,
        compare_at_price: 79.9,
        price: 63.92,
        external_site: 'De Corpo Moda Fitness Oficial',
        external_url: 'https://www.decorpo.com.br/acessorios/manguito-ice-touch',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 83,
        sizes: ['P', 'M', 'G'],
        colors: ['Preto'],
        composition: 'Poliamida com tecnologia refrigerante Ice Touch e proteção UPF50+',
        description:
          'Protege os braços contra insolação mantendo sensação de frio durante pedaladas e corridas.',
        images_urls: [
          'https://img.usecurling.com/p/600/600?q=uv%20protective%20arm%20sleeves%20black&color=black',
        ],
      },

      // ==========================================
      // 6. WONDERSIZE (11 produtos - 20% OFF)
      // "Referência em moda fitness e inclusiva com foco no segmento plus size."
      // ==========================================
      {
        name: 'Legging Joana Dark Tecnológica WonderSize Preta',
        slug: 'legging-joana-dark-tecnologica-wondersize-preta',
        category: 'leggings',
        brand: 'WonderSize',
        external_price: 279.9,
        compare_at_price: 279.9,
        price: 223.92,
        external_site: 'Wonder Size Loja Oficial',
        external_url:
          'https://www.wondersize.com.br/en/product-page/legging-joana-dark-tecnol%C3%B3gica',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: true,
        rating: 5.0,
        rating_count: 156,
        sizes: ['GG', 'G1', 'G2', 'G3', 'G4'],
        colors: ['Preto'],
        composition: 'Nanotecnologia em poliamida com alta compressão sem transparência',
        description:
          'Referência em moda fitness e inclusiva com foco no segmento plus size. A consagrada legging Joana Dark com cós ultra anatômico de sustentação e nanotecnologia exclusiva.',
        images_urls: [
          'https://static.wixstatic.com/media/68a621_ddd15ebd62bc4dfab15e2b918be5b5b5~mv2.png/v1/fill/w_600,h_800,al_c,q_85,enc_auto/68a621_ddd15ebd62bc4dfab15e2b918be5b5b5~mv2.png',
        ],
      },
      {
        name: 'Legging Joana Dark com Bolso Tecnológica WonderSize',
        slug: 'legging-joana-dark-com-bolso-tecnologica-wondersize',
        category: 'leggings',
        brand: 'WonderSize',
        external_price: 309.9,
        compare_at_price: 309.9,
        price: 247.92,
        external_site: 'Wonder Size Loja Oficial',
        external_url:
          'https://www.wondersize.com.br/en/product-page/legging-joana-dark-com-bolso-tecnol%C3%B3gica',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 114,
        sizes: ['GG', 'G1', 'G2', 'G3', 'G4'],
        colors: ['Preto'],
        composition: 'Poliamida nanotecnológica com bolso lateral profundo',
        description:
          'A versão com bolsos funcionais da Joana Dark, sustentação reforçada que não enrola no abdômen plus size.',
        images_urls: [
          'https://static.wixstatic.com/media/b43615_f930144ee58d415a92fbb82d568d2117~mv2.jpg/v1/fill/w_600,h_800,al_c,q_80,enc_auto/b43615_f930144ee58d415a92fbb82d568d2117~mv2.jpg',
        ],
      },
      {
        name: 'Calça Flare Bailarina Denise com Bolso Emana WonderSize',
        slug: 'calca-flare-bailarina-denise-com-bolso-emana-wondersize',
        category: 'calcas',
        brand: 'WonderSize',
        external_price: 329.9,
        compare_at_price: 329.9,
        price: 263.92,
        external_site: 'Wonder Size Loja Oficial',
        external_url:
          'https://www.wondersize.com.br/en/product-page/bailarina-flare-com-bolso-emana',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: true,
        rating: 4.9,
        rating_count: 98,
        sizes: ['GG', 'G1', 'G2', 'G3'],
        colors: ['Preto'],
        composition: 'Fio inteligente Emana com corte flare bailarina e bolso tecnológico',
        description:
          'Bailarina plus size desenvolvida para modelar sem comprimir em excesso, ativando a circulação sanguínea com o fio Emana.',
        images_urls: [
          'https://static.wixstatic.com/media/68a621_dc0a1478043842f3ac54315b0c746004~mv2.png/v1/fill/w_600,h_800,al_c,q_85,enc_auto/68a621_dc0a1478043842f3ac54315b0c746004~mv2.png',
        ],
      },
      {
        name: 'Corsário Najara com Bolso Tecnológico Emana WonderSize',
        slug: 'corsario-najara-com-bolso-tecnologico-emana-wondersize',
        category: 'calcas',
        brand: 'WonderSize',
        external_price: 269.9,
        compare_at_price: 269.9,
        price: 215.92,
        external_site: 'Wonder Size Loja Oficial',
        external_url: 'https://www.wondersize.com.br/en/product-page/cors%C3%A1rio-com-bolso-emana',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 73,
        sizes: ['GG', 'G1', 'G2', 'G3'],
        colors: ['Preto'],
        composition: 'Fio Emana de alta sustentação comprimento corsário',
        description:
          'Comprimento abaixo do joelho que não sobe, ideal para mobilidade, caminhada e musculação com máximo conforto.',
        images_urls: [
          'https://static.wixstatic.com/media/68a621_703a12f4dcef4a05bca14d84ea625049~mv2.png/v1/fill/w_600,h_800,al_c,q_85,enc_auto/68a621_703a12f4dcef4a05bca14d84ea625049~mv2.png',
        ],
      },
      {
        name: 'Top Phelps Estruturado Zíper Frontal WonderSize',
        slug: 'top-phelps-estruturado-ziper-frontal-wondersize',
        category: 'camisetas',
        brand: 'WonderSize',
        external_price: 219.9,
        compare_at_price: 219.9,
        price: 175.92,
        external_site: 'Wonder Size Loja Oficial',
        external_url: 'https://www.wondersize.com.br/en/colecoes/top-phelps',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: true,
        rating: 5.0,
        rating_count: 87,
        sizes: ['GG', 'G1', 'G2', 'G3', 'G4'],
        colors: ['Preto'],
        composition: 'Poliamida estruturada com fecho de zíper frontal com trava e alças largas',
        description:
          'Sustentação poderosa para bustos volumosos com abertura frontal prática e costas nadador de suporte ergonômico.',
        images_urls: [
          'https://static.wixstatic.com/media/aaeb68_a4dc103667c2408ea18a96f94b9132a4~mv2.jpg/v1/fill/w_600,h_800,al_c,q_80,enc_auto/aaeb68_a4dc103667c2408ea18a96f94b9132a4~mv2.jpg',
        ],
      },
      {
        name: 'Shorts Saia Esther WonderSize Plus Size',
        slug: 'shorts-saia-esther-wondersize-plus-size',
        category: 'shorts',
        brand: 'WonderSize',
        external_price: 249.9,
        compare_at_price: 249.9,
        price: 199.92,
        external_site: 'Wonder Size Loja Oficial',
        external_url: 'https://www.wondersize.com.br/en/colecoes/shorts-saia-esther',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 65,
        sizes: ['GG', 'G1', 'G2', 'G3'],
        colors: ['Preto'],
        composition: 'Short interno compressivo antiassadura e saia em poliamida fluida',
        description:
          'Estilo feminino com proteção interna completa entre as pernas que evita qualquer atrito incômodo.',
        images_urls: [
          'https://static.wixstatic.com/media/aaeb68_3130cde842044e4eac5e781439fce6f8~mv2.jpg/v1/fill/w_600,h_800,al_c,q_80,enc_auto/aaeb68_3130cde842044e4eac5e781439fce6f8~mv2.jpg',
        ],
      },
      {
        name: 'Bermuda Ciclista Hebe Alta Compressão WonderSize',
        slug: 'bermuda-ciclista-hebe-alta-compressao-wondersize',
        category: 'shorts',
        brand: 'WonderSize',
        external_price: 199.9,
        compare_at_price: 199.9,
        price: 159.92,
        external_site: 'Wonder Size Loja Oficial',
        external_url: 'https://www.wondersize.com.br/loja?Categorias=Shorts',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 92,
        sizes: ['GG', 'G1', 'G2', 'G3', 'G4'],
        colors: ['Preto'],
        composition: 'Poliamida reforçada com cós anatômico de 14cm',
        description:
          'Bermuda ciclista plus size que não enrola na barriga e mantém a firmeza durante todo o treino.',
        images_urls: [
          'https://static.wixstatic.com/media/aaeb68_ba5c8c65ab0d44948b70de873d81f4f7~mv2.jpg/v1/fill/w_600,h_800,al_c,q_80,enc_auto/aaeb68_ba5c8c65ab0d44948b70de873d81f4f7~mv2.jpg',
        ],
      },
      {
        name: 'Camiseta Dry Flow WonderSize Ampla Terracota',
        slug: 'camiseta-dry-flow-wondersize-ampla-terracota',
        category: 'camisetas',
        brand: 'WonderSize',
        external_price: 169.9,
        compare_at_price: 169.9,
        price: 135.92,
        external_site: 'Wonder Size Loja Oficial',
        external_url: 'https://www.wondersize.com.br/loja?Categorias=Camisetas',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 53,
        sizes: ['GG', 'G1', 'G2', 'G3'],
        colors: ['Terracota'],
        composition: 'Tecido Dry respirável com caimento solto e alongado',
        description:
          'Modelagem pensada para o corpo curvilíneo, com comprimento que cobre o quadril e tecido antissuor.',
        images_urls: [
          'https://img.usecurling.com/p/600/750?q=plus%20size%20workout%20tshirt%20terracotta&color=orange',
        ],
      },
      {
        name: 'Regata Nadador WonderSize Confort Plus Preta',
        slug: 'regata-nadador-wondersize-confort-plus-preta',
        category: 'regatas',
        brand: 'WonderSize',
        external_price: 149.9,
        compare_at_price: 149.9,
        price: 119.92,
        external_site: 'Wonder Size Loja Oficial',
        external_url: 'https://www.wondersize.com.br/loja?Categorias=Regatas',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.7,
        rating_count: 48,
        sizes: ['GG', 'G1', 'G2', 'G3'],
        colors: ['Preto'],
        composition: 'Viscolycra com elastano encorpada',
        description:
          'Cavas anatômicas que não apertam as axilas e garantem total ventilação para a rotina esportiva.',
        images_urls: [
          'https://img.usecurling.com/p/600/750?q=plus%20size%20athletic%20tank%20black&color=black',
        ],
      },
      {
        name: 'Jaqueta Bomber Corta-Vento WonderSize Plus Preto',
        slug: 'jaqueta-bomber-corta-vento-wondersize-plus-preto',
        category: 'jaquetas',
        brand: 'WonderSize',
        external_price: 349.9,
        compare_at_price: 349.9,
        price: 279.92,
        external_site: 'Wonder Size Loja Oficial',
        external_url: 'https://www.wondersize.com.br/loja?Categorias=Jaquetas',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.9,
        rating_count: 41,
        sizes: ['GG', 'G1', 'G2', 'G3'],
        colors: ['Preto'],
        composition: 'Poliéster corta-vento leve com zíper frontal reforçado',
        description:
          'Estilo bomber urbano contemporâneo projetado exclusivamente para a silhueta plus size.',
        images_urls: [
          'https://img.usecurling.com/p/600/750?q=plus%20size%20bomber%20jacket%20sporty%20black&color=black',
        ],
      },
      {
        name: 'Faixa de Resistência Elástica WonderSize Loop Band',
        slug: 'faixa-de-resistencia-elastica-wondersize-loop-band',
        category: 'acessorios',
        brand: 'WonderSize',
        external_price: 79.9,
        compare_at_price: 79.9,
        price: 63.92,
        external_site: 'Wonder Size Loja Oficial',
        external_url: 'https://www.wondersize.com.br/loja?Categorias=Acessorios',
        price_verified_at: '25/02/2025',
        is_on_sale: true,
        is_featured: false,
        rating: 4.8,
        rating_count: 72,
        sizes: ['Tamanho Único (Carga Média/Pesada)'],
        colors: ['Lilás / Preto'],
        composition:
          'Tecido elástico de alta densidade com fita emborrachada interna antiderrapante',
        description:
          'Faixa elástica larga para ativação de glúteos e pernas, que não enrola nem belisca a pele.',
        images_urls: [
          'https://img.usecurling.com/p/600/600?q=fitness%20resistance%20fabric%20booty%20band&color=purple',
        ],
      },
    ]

    for (const item of newBrandProducts) {
      try {
        // Idempotência: não duplica se já existir slug
        try {
          app.findFirstRecordByData('products', 'slug', item.slug)
          continue
        } catch (_) {}

        const rec = new Record(productsCol)
        rec.set('name', item.name)
        rec.set('slug', item.slug)
        rec.set('description', item.description)
        rec.set('category', item.category)
        rec.set('price', Number(item.price.toFixed(2)))
        rec.set('compare_at_price', Number(item.compare_at_price.toFixed(2)))
        rec.set('brand', item.brand)
        rec.set('external_url', item.external_url)
        rec.set('external_price', Number(item.external_price.toFixed(2)))
        rec.set('external_site', item.external_site)
        rec.set('price_verified_at', item.price_verified_at)
        rec.set('is_on_sale', true)
        rec.set('is_featured', !!item.is_featured)
        rec.set('inventory', 100)
        rec.set('sizes', item.sizes)
        rec.set('colors', item.colors)
        rec.set('rating', item.rating)
        rec.set('rating_count', item.rating_count)
        rec.set('composition', item.composition)
        rec.set('images_urls', item.images_urls)
        app.save(rec)
      } catch (err) {
        console.log(`Failed inserting item ${item.name}:`, err)
      }
    }
  },
  (app) => {
    // down migration
  },
)
